export default {
    SET_ERROR: 'SET_ERROR',
    SET_MOVIES: 'SET_MOVIES',
    ADD_MOVIE: 'ADD_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    ADD_GRAPHQL_ERROR: 'ADD_GRAPHQL_ERROR',
    SAVE_TOKEN: 'SAVE_TOKEN',
    SET_USER_LOADED: 'SET_USER_LOADED',
    SET_USER: 'SET_USER',
};